### ISSUE TITLE
Working example

### ISSUE THREAD

**Issue by edimoldovan** [auth0/hapi-auth-jwt#3]
Could you please provide a working example? I’ve been trying to put it together but wasn’t able.

**Comment by dschenkelman** [comment]
Are you having trouble with anything in particular? You can take a look at the unit tests for the [dynamic keys feature](https://github.com/auth0/hapi-auth-jwt/blob/master/test/dynamicKeys.tests.js) which provide a working example.

If you still can't get it to work please provide more details and we will hep you gladly.

**Comment by edimoldovan** [comment]
Yes, I tried running the example and could not. This is one.
The other one is that when I do server.register (...) I don’t know what the first param should be. I thought of a working example because it would be maybe easier to see it in practice.

**Comment by dschenkelman** [comment]
Sure. I'm a bit short of time right now but will try to post something here once I have a bit of time.

**Comment by dschenkelman** [comment]
This is based on our usage (of course parts were removed) but the basic gist is there:

```
var jws = require('jws');

function validateFunc (decoded_token, additional_info, callback) {
  // here the token's signature has already been checked
  // create the credentials object and invoke callback
  callback(null, true, decoded_token);
}

function keyFunc(token, callback){
    var decoded_token = jws.decode(token);
    var decoded_header = decoded_token.header;
    var decoded_payload = decoded_token.payload;

   // login to retrieve signing key based on token's contents goes here...
   callback(null, key, { /* additional info required in validateFunc*/ });
}

server.register([require('hapi-auth-jwt')] , function (err) {
    if (err) {
      throw err; // something bad happened loading the plugins
    }

    server.auth.strategy('jwt', 'jwt', {
      validateFunc: validateFunc,
      key: keyFunc,
    });
});
```

**Comment by edimoldovan** [comment]
Helps a lot, thank you for putting time into it!

**Comment by eventhough** [comment]
@dschenkelman What's the purpose of the extraInfo parameter that was added to the validateFunc? Is that just for testing? Thanks.

https://github.com/auth0/hapi-auth-jwt/blob/master/lib/index.js#L78

**Comment by dschenkelman** [comment]
@eventhough in our API we have a couple of DB queries that are performed in the `keyFunc` and some of the data returned by those queries is also necessary in `validateFunc`. To avoid performing the query multiple times, and since it is all part of the auth process we are passing that information (one could call it `context`) through that object.
